# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 02:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u83dc\u540d')),
                ('price', models.IntegerField(default=0, verbose_name='\u4ef7\u683c')),
                ('category', models.CharField(choices=[('rh', '\u70ed\u8364'), ('rs', '\u70ed\u7d20'), ('lc', '\u51c9\u83dc'), ('td', '\u751c\u70b9'), ('zs', '\u4e3b\u98df'), ('js', '\u9152\u6c34')], default='rh', max_length=5, verbose_name='\u83dc\u7684\u7c7b\u522b')),
                ('image', models.ImageField(upload_to='food/%Y/%m', verbose_name='\u56fe\u7247')),
                ('taste', models.CharField(max_length=20, verbose_name='\u53e3\u5473')),
                ('detail', models.TextField(verbose_name='\u8be6\u7ec6\u63cf\u8ff0')),
                ('buy_nums', models.IntegerField(default=0, verbose_name='\u4e0b\u5355\u6570')),
                ('fav_nums', models.ImageField(default=0, upload_to=b'', verbose_name='\u6536\u85cf\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u83dc\u5355',
                'verbose_name_plural': '\u83dc\u5355',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_pay', models.BooleanField(default=False, verbose_name='\u662f\u5426\u652f\u4ed8')),
                ('total_money', models.IntegerField(default=0, verbose_name='\u603b\u91d1\u989d')),
                ('order_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0b\u5355\u65f6\u95f4')),
                ('preset_time', models.CharField(default='', max_length=20, verbose_name='\u9884\u8ba2\u65f6\u95f4')),
                ('room_num', models.CharField(default='', max_length=5, verbose_name='\u5305\u95f4\u53f7')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Food', verbose_name='\u83dc\u5355')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Order', verbose_name='\u8ba2\u5355')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u8be6\u60c5',
                'verbose_name_plural': '\u8ba2\u5355\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u5305\u95f4\u540d')),
                ('category', models.CharField(choices=[('big', '12\u4eba\u95f4'), ('middle', '8\u4eba\u95f4'), ('small', '6\u4eba\u95f4')], max_length=8, verbose_name='\u79cd\u7c7b')),
                ('has_order', models.BooleanField(default=False, verbose_name='\u662f\u5426\u9884\u8ba2')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5305\u95f4',
                'verbose_name_plural': '\u5305\u95f4',
            },
        ),
    ]
