# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food/%Y/%m', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='order',
            name='preset_time',
            field=models.DateTimeField(verbose_name='\u9884\u8ba2\u65f6\u95f4'),
        ),
    ]
